### ISSUE TITLE
do not allow `commit` in `prepare` context

### ISSUE THREAD

**Issue by peckato1** [CESNET/netconf-cli#19]
I think it is very misleading that you can write something like

```
prepare /mod:rpc
commit
```

I got stuck here because I wanted to use `exec` but for some reason I used `commit` accidentally.

Or is there an usecase where you want to `commit` while editing RPC's input nodes?

**Comment by jktjkt** [comment]
> Or is there an usecase where you want to `commit` while editing RPC's input nodes?

Nope, that should be prevented IMHO. It's expected to be an either-or.

**Comment by peckato1** [comment]
Now I see that it is already a WIP https://gerrit.cesnet.cz/c/CzechLight/netconf-cli/+/6612
